name: 'FTP Deploy'
description: 'Syncs files via FTP/SFTP to a remote server'
author: 'Sam Kirkland'
inputs:
  ftp-server:
    description: 'Deployment destination server & path. Formatted as protocol://domain.com:port/full/destination/path/'
    required: true
  ftp-username:
    description: 'FTP account username'
    required: true
  ftp-password:
    description: 'FTP account password'
    required: false
  sftp-key:
    description: 'SFTP account key'
    required: false
  local-dir:
    description: 'The local folder to copy, defaults to root project folder'
    default: ./
    required: false
  git-ftp-args:
    description: 'Passes through options into git-ftp'
    default: 
    required: false
  known-hosts:
    description: The desired content of your `.ssh/known_hosts` file
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'upload-cloud'
  color: 'orange'
